#ifndef QUANTUMTASK_H
#define QUANTUMTASK_H

#include <llvm/ExecutionEngine/Orc/ThreadSafeModule.h>

// #include <qdmi/client.h>
#include <qdmi/constants.h>
#include <qdmi.hpp>

#include <ctime>
#include <memory>
#include <string>
#include <time.h>

using llvm::orc::ThreadSafeModule;
using namespace std;

/**
 * @brief The QuantumTask struct, representing a quantum circuit to be executed
 * on a QDMI device
 *
 * A QuantumTask is a task that can be executed on a QDMI device. It contains
 * all the necessary information to execute the task, such as the number of
 * qubits, the number of shots, the circuit to be executed, the expected
 * execution time, and the execution order. The task can also have a parent task
 * if it was generated by cutting a larger task.
 */
struct QuantumTask {
  int TaskId;                              // Identifier of the task
  int NumberQbits;                         // Number of requested qubits
  int NumberShots;                         // Number of requested shots
  string CircuitFile;
  string CircuitFileType;
  string ResultsDestination;
  std::shared_ptr<QuantumTask> ParentTask; // Parent task             
  float Duration; // Expected execution time
  float Age;      // Prevents starvation in the queue
  float End;      // Predicted time of completion (incl. its wait time in queue)
  double ExecutionOrder; // Decides on position in the queue
  int Priority;
  int ResultType;
  int OptimisationLevel;
  bool NoModify;  // Keep circuit as is (no optimisation)
  bool TranspilerFlag;
  time_t SubmitTime;
  string CircuitQiskit;
  string AdditionalInformation;
  string ChangeGenerator;
  string ChangeSelector;
  string ChangeScheduler;
  ThreadSafeModule SubmitterThreadSafeModule;

  QuantumTask(int id) : TaskId(id) { };
};

#endif