ClusterName=mqss-spank-testbed
SlurmctldHost=localhost(127.0.0.1)
SlurmUser=slurm
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmdLogFile=/var/log/slurmd.log
SlurmctldLogFile=/var/log/slurmctld.log
ProctrackType=proctrack/pgid
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
TaskPlugin=task/none
SlurmdParameters=config_overrides
PlugStackConfig=/etc/slurm/plugstack.conf
GresTypes=qpu
Licenses=mqss_iqm_eqe1:1,mqss_iqm_eqe1_mock:1,mqss_iqm_qexa:1,mqss_aqt:1,mqss_qlm:1
NodeName=localhost NodeAddr=127.0.0.1 CPUs=8 Gres=qpu:iqm_eqe1:1,qpu:iqm_eqe1_mock:1,qpu:iqm_qexa:1,qpu:aqt:1,qpu:qlm:1 State=UNKNOWN
PartitionName=mqss Nodes=localhost Default=YES MaxTime=INFINITE State=UP
