#!/usr/bin/env bash
echo "Running experiments for the circuits with 2 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/2_qubits"
echo "--------------------------------------------------"
echo " "
echo "Running experiments for the circuits with 3 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/3_qubits"
echo "--------------------------------------------------"
echo " "
echo "Running experiments for the circuits with 4 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/4_qubits"
echo "--------------------------------------------------"
echo " "
echo "Running experiments for the circuits with 5 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/5_qubits"
echo "--------------------------------------------------"
echo " "
echo "Running experiments for the circuits with 6 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/6_qubits"
echo "--------------------------------------------------"
echo " "
echo "Running experiments for the circuits with 7 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/7_qubits"
echo "--------------------------------------------------"
echo " "
echo "Running experiments for the circuits with 8 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/8_qubits"
echo "--------------------------------------------------"
echo " "
echo "Running experiments for the circuits with 9 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/9_qubits"
echo "--------------------------------------------------"
echo " "
echo "Running experiments for the circuits with 10 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/10_qubits"
echo "--------------------------------------------------"
echo " "
echo "Running experiments for the circuits with 11 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/11_qubits"
echo "--------------------------------------------------"
echo " "
echo "Running experiments for the circuits with 12 qubits"
python sim_qcircuits_ibm_fake_backends.py --input="../data/benchmark_circuits/mqtbench_circuits/12_qubits"
echo "--------------------------------------------------"
echo " "